# Generated by Django 5.1.6 on 2025-02-25 10:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.FloatField(default=0)),
                ('filters', models.JSONField()),
                ('stats', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('date', models.DateTimeField()),
                ('priority', models.FloatField(blank=True, null=True)),
                ('changefreq', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sitemap_manager.scrapertask')),
            ],
        ),
    ]
